preset: symfony

finder:
    path:
        - "src"
        - "tests"

disabled:
    - blank_line_before_break
    - blank_line_before_continue
    - blank_line_before_declare
    - blank_line_before_return
    - blank_line_before_throw
    - blank_line_before_try

enabled:
    - short_array_syntax

